image: node:carbon-alpine

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - lint
  - release
  - deploy

# Stage I
# Testing Phase:
# This is where the main code is tested.
# Other options like code coverage, etc are also written in this phase
test:
  stage: test
  script:
   - rm -rf package-lock.json
   - npm install
   - npm run test:unit
   - npm run lint
   #- ./node_modules/.bin/codecov --token="$CODECOV_TOKEN"


# Stage II
# Build Phase:
# This is where the main code is tested.
build:
  stage: build
  script:
    - rm -rf package-lock.json
    - npm install @vue/cli
    - npm install
    - npm run build
  artifacts:
    paths:
      #build folder
      - dist/

# Stage III
# Deployment Phase:
# This is where the main code is deployed
.deploy_staging:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build . -t registry.gitlab.com/lucianosz7/20192-arbc_arbc_app:$DOCKERTAG

    - docker login "$DOCKERLOGIN" -p "$DOCKERPASSWORD" registry.gitlab.com

    - docker push registry.gitlab.com/lucianosz7/20192-arbc_arbc_app:$DOCKERTAG
    
release_development:
  extends: .deploy_staging
  environment: development
  only:
    - master


