image: node:carbon-alpine

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - deploy

# Stage I
# Testing Phase:
# This is where the main code is tested.
# Other options like code coverage, etc are also written in this phase
test:
  stage: test
  script:
   - rm -rf package-lock.json
   - npm install
   - npm install -g codacy-coverage --save
   - npm run jest:update
   - npm run test:unit
   - npm run lint
   - npm run coverage

# Stage II
# Build Phase:
# This is where the main code is built
build:
  stage: build
  script:
    - rm -rf package-lock.json
    - npm install @vue/cli
    - npm install
    - npm run build
  artifacts:
    paths:
      #build folder
      - dist/
      

# Stage III
# Release Phase
# At this stage our application is deployed
.release:
  stage: deploy
  script:
    - rm -rf package-lock.json

    - npm install
    - npm i -g netlify-cli
    - npm run build
  dependencies:
    - build

release_development:
  extends: .release
  environment: 
    name: development
    url: https://arbc-dev.netlify.com/
  only: 
    - update_pipeline

release_staging:
  extends: .release
  environment: 
    name: staging
    url: https://arbc-stg.netlify.com/
  only: 
    - update_pipeline
    
release_production:
  extends: .release
  environment: 
    name: production
    url: https://arbc.netlify.com/
  only:
    - update_pipeline

