image: node:carbon-alpine

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - deploy

# Stage I
# Testing Phase:
# This is where the main code is tested.
# Other options like code coverage, etc are also written in this phase
test:
  stage: test
  script:
   - rm -rf package-lock.json
   - npm install
   # - npm run test:unit
   - npm run lint
   - npm install -g codacy-coverage --save
   #- npm run test:unit -u --coverage && cat ./coverage/lcov.info | codacy-coverage --accountToken $CODACY_ACCOUNT_TOKEN --username $USER_CODACY --projectName 2019.2-ArBC
   - npm run jest:update 
   - npm run codacy | codacy-coverage --token $CODECOV_TOKEN
# Stage II
# Build Phase:
# This is where the main code is built
build:
  stage: build
  script:
    - rm -rf package-lock.json
    - npm install @vue/cli
    - npm install
    - npm run build
  artifacts:
    paths:
      #build folder
      - dist/
      

# Stage III
# Release Phase
# At this stage our application is deployed
.release:
  stage: deploy
  script:
    - rm -rf package-lock.json

    - npm install
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
    
release_production:
  extends: .release
  environment: production
  only:
    - tags
  except:
   - ^(?!master).+@/

release_development:
  extends: .release
  environment: 
    name: development
    url: https://arbc-lab.netlify.com
  only: 
    - master

