image: node:carbon-alpine

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

# Stage I
# Testing Phase:
# This is where the main code is tested.
# Other options like code coverage, etc are also written in this phase
test:
  stage: test
  script:
   - rm -rf package-lock.json
   - npm install
   - npm run test:unit
   - npm run lint
   #- ./node_modules/.bin/codecov --token="$CODECOV_TOKEN"


# Stage II
# Build Phase:
# This is where the main code is built.
build:
  stage: build
  script:
    - rm -rf package-lock.json
    - npm install @vue/cli
    - npm install
    - npm run build
  artifacts:
    paths:
      #build folder
      - dist/



